### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Borzoff** [LielXD/CS2-WeaponPaints-Website#1]
26078#26078: *4205 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_contains() in /var/www/skins/public/skins/index.php:147
Stack trace:
#0 {main}
  thrown in /var/www/skins/public/skins/index.php on line 147" while reading response header from upstream

**Comment by Borzoff** [comment]
Maybe it's because of the PHP version?

**Comment by LielXD** [comment]
Minimum version should be 8.0.
please update your php.
