### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by Borzoff** [LielXD/CS2-WeaponPaints-Website#12]
the site doesn't display the weapons in Steam overlay
![20240215010506_1](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/59200516/6799a4c1-0b8b-4fb0-8e7a-03e3425e1c27)

**Comment by LielXD** [comment]
Have you download the latest version?

**Comment by Borzoff** [comment]
> Have you download the latest version?

Installed the new version, same problem

**Comment by LielXD** [comment]
Then you have you have you chache problem please CTRL + F5
