### ISSUE TITLE
false?

### ISSUE THREAD

**Issue by asdfxD** [LielXD/CS2-WeaponPaints-Website#14]
can't download your latest zip.

![zip](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/24253340/2d45a4e7-a26f-47e2-b82f-1c7d4aed36e4)

Edit: Download from release works, but downloading from "CODE" button gives trojan warning. :D

**Comment by LielXD** [comment]
wtf

**Comment by LielXD** [comment]
Please download again.
