### ISSUE TITLE
issue with selecting skin wear

### ISSUE THREAD

**Issue by xMin3S** [LielXD/CS2-WeaponPaints-Website#19]
https://github.com/LielXD/CS2-WeaponPaints-Website/assets/58640055/926da2d8-5a9b-4615-96e3-8b661e6a11d4

**Comment by asdfxD** [comment]
same here. choose field tested for example it will goes one above and use minimal wear or select battle scared it uses well worn.

**Comment by LielXD** [comment]
Fixed by v1.3.3,
please update.
