### ISSUE TITLE
[BUG] No translations have found contact support

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#21]
I did the installation and configuration correctly but I only get the error.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/acbb0344-81ea-45df-a014-3d1c79a47946)

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/2903b6a3-fe35-4d11-894a-d535632368b1)

**Comment by LielXD** [comment]
Your website is working its saying to me that your database credentials is not right?
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/60383662/1334953e-b375-4cf2-8e3d-6c6cbdee6ef7)

**Comment by crashzk** [comment]
Database data would be fine too, I checked both the website and the database credentials and everything was fine.

Using PHP 8.2.

I tested the original web version of the plugin, everything worked fine with the same data from the database.

**Comment by LielXD** [comment]
so the website is working for u now or no?

**Comment by crashzk** [comment]
Nop.

https://cs2.zkservidores.com/

**Comment by crashzk** [comment]
I left these settings blank:
```
// If you store your website on a subfolder domain,
// Leave empty if using the domain as normal.
// Example: cs2.lielxd.com/cs2/ | then we need here cs2 ↓
$Website_Subfolder = '';

// Place here your domain if steam authorize not working properly,
// if its working good then leave it empty.
$Website_Domain = '';
```
Solved the problem, now everything works.

https://cs2.zkservidores.com/
