### ISSUE TITLE
[REQ] Option for multiple servers

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#23]
When we access the website without logging in via Steam we see the following information:

https://cs2.lielxd.com/

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/b530a3bb-7fec-4eac-a3f7-6c1d6d7b4518)

As you can see in the print by clicking on `CS2.LIELXD.COM` we connect to the server cs2. This option is editable in the translations file.

Would it be possible to add an option for multiple servers? It would still show a server, but whenever the page reloads it will show a new server to configure.

Example:
```
"login": {
        "header": "ZK Servidores™ - Melhores Servidores da Comunidade BR",
        "title": "COMPETITIVO",
        "title_link": "steam://connect/45.179.91.41:27176?appid=730",

        "title": "COMPETITIVO 2",
        "title_link": "steam://connect/45.179.91.41:27176?appid=730",

        "title": "COMPETITIVO 3",
        "title_link": "steam://connect/45.179.91.41:27176?appid=730",

        "title": "COMPETITIVO 4",
        "title_link": "steam://connect/45.179.91.41:27176?appid=730",

        "title_hover": "Conecte-se ao servidor",
        "footer": "Faça login através da Steam para continuar",
        "button": "Entrar com a Steam"
    },
  ```

**Comment by LielXD** [comment]
Added by new release.
