### ISSUE TITLE
[REQ] Background improvements

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#24]
The random color system is interesting, but why not the CS2 background option, like it has in the game.

Something like the project: https://inventory.cstrike.app/

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/a6389bb4-90bb-4f3c-9706-9d9107e421fc)

Optionally put Random Colors and images from the game as background.

**Comment by LielXD** [comment]
This is the style of the website its not meant to be like the in game menu...

**Comment by asdfxD** [comment]
Yes, pls don't change the style of this site!!

**Comment by crashzk** [comment]
I understand, and in relation to the `$Website_MainColor` option.
```
// You can choose your own theme color
// false/empty - will use the default color.
// any html acceptable color - will display that color.
// true - this will make get a random color.
$Website_MainColor = true;
```

Would it be possible to implement it in the website settings so that we can choose the color directly or a random color? This way, each user could choose their theme;

**Comment by LielXD** [comment]
Yes I can add this to the settings menu,
next update.
