### ISSUE TITLE
[REQ] Missing translations?

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#25]
Choose your knife
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/6c84a481-2c86-46d2-ad93-4f748032b1d3)

Choose your gloves
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/a60a8b18-0dee-42b9-ae74-a867d4dbf21f)

Or even translation for each category:
- Choose your Pistol
- Choose your Rifles
- Choose your Knife
- Choose your Gloves
- etc...

**Comment by LielXD** [comment]
It should be Choose your **weapon**.

**Comment by crashzk** [comment]
> It should be Choose your **skin**, please update your translation.

Yes, I changed it in this case. I thought if this feature would be possible, with greater freedom to translate each category, let's say.

**Comment by LielXD** [comment]
will work on it for next update.

**Comment by LielXD** [comment]
Added.
