### ISSUE TITLE
[BUG] Change Wear & Seed with skin already selected

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#26]
If you choose a skin, for example **Sports Gloves - Vice | Factory New** and then try to change the wear, the change is not made, even if you click to change. I reload the page and it doesn't change the wear.

Same bug applies to Seed.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/b3f2fb02-31ec-425a-8ff1-e4b31799de4d)

**Comment by LielXD** [comment]
For me it's working please check again.

**Comment by crashzk** [comment]
> For me it's working please check again, Or give any steps to reproduce the bug.

1. First log in.
2. Choose a skin from **Faca** to **Bayonet**, in my test I chose the **Fade** skin, just change the skin **do not change the Seed or Wear of the skin**.
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/997dba23-4f97-4877-84e1-e54af82e03e4)
3. Then go back to the **Knife** category and select **Bayonet** and the **Fade** skin again, and change its Seed or Wear, you will see that the change is not saved, there would not be a button to **save/use.**

This occurs for any skin, weapon, glove or knife.

**Comment by LielXD** [comment]
Fixed by v1.3.6.
