### ISSUE TITLE
[BUG] Theme option does not work

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#27]
I click to change the **Them**e but nothing happens, nothing opens.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/562f9758-58ee-4747-9fc8-bd41ed2a9cf7)

The configuration appears to be ok:
```
// Select which settings you want in the menu.
$Website_Settings = [
    'language' => true,  // user can select his own language.
    'theme' => true      // user can change his own color theme.
];
```

**Comment by crashzk** [comment]
For some reason, it now works.

**Comment by LielXD** [comment]
It's a cache problem that's why it's working from nowhere.
