### ISSUE TITLE
Blank Page after login

### ISSUE THREAD

**Issue by KillerRoi** [LielXD/CS2-WeaponPaints-Website#29]
Blank page after login
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/54289708/0b42be8e-e444-4184-a923-3d2db5190e06)
Fatal error: Uncaught ErrorException: Connection timed out after 30000 milliseconds in /var/www/html/skins/includes/openid.php:284 Stack trace: #0 /var/www/html/skins/includes/openid.php(480): LightOpenID->request_curl() #1 /var/www/html/skins/includes/openid.php(638): LightOpenID->request() #2 /var/www/html/skins/includes/openid.php(857): LightOpenID->discover() #3 /var/www/html/skins/includes/authorize.php(31): LightOpenID->authUrl() #4 {main} thrown in /var/www/html/skins/includes/openid.php on line 284

**Comment by LielXD** [comment]
try refresh the page with CTRL + F5 to clear the cache and tell me if its the same.

**Comment by KillerRoi** [comment]
Same even after doing that, it doesn't go to steam.

**Comment by KillerRoi** [comment]
https://cdn.discordapp.com/attachments/912715770193117274/1213148187641122846/Screenshot_2024-03-01_183740.png?ex=65f46b4b&is=65e1f64b&hm=921addb1e372f5aa553e31adff18f8280b2001b4368fa9bd2d5f0f3d14353cd4&

This is what I'm getting now

**Comment by LielXD** [comment]
I've sign in to your website and worked fine maybe some issue with steam try again tomorrow and tell me if its still throwing error.

**Comment by KillerRoi** [comment]
I found a fix
