### ISSUE TITLE
[REQ] Support for choosing skins for CT and TR

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#3]
Would it be possible to implement support for choosing skins for each team? CT with his kit and TR with his skin kit.

**Comment by LielXD** [comment]
Currently this project is only a website for managing skins according to the plugin CS2-WeaponPaints,
to make a separate skins for t and ct it needs to be supported by the plugin so all I can tell you to do is to ask in the github repository of the plugins and once it will get update I will update too.
