### ISSUE TITLE
[REQ] Default skins always as the first option in categories

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#36]
I noticed that the default CS2 skins are not in first place in the categories.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/7013b3ba-96da-49a9-b9ef-60e732e7c9ca)

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/3e29b7fa-a527-4316-99e3-6593094386b7)

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/2be35dda-86b7-4cbf-9b0e-d22f8ef729de)

Wouldn't it be possible for the default CS2 skin to always be in first position? This applies to all categories, skins, knives, gloves and agents.

**Comment by LielXD** [comment]
Update v1.4.0.
