### ISSUE TITLE
[REQ] Default gloves select direct

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#37]
If I want to put on the Default CS2 gloves, I need to choose it and then select it.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/5481699e-fb5f-414f-b4e0-e40e5405a94a)

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/eccd9783-b2a2-4f54-b1fe-d2662c7ea756)

It would be possible to make it so that just by clicking directly on the Default Gloves it changes to the default, without opening the glove and then choosing it.

**Comment by LielXD** [comment]
meant to be that way.
