### ISSUE TITLE
[REQ] Translation improvements for categories

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#38]
Currently the categories have this option for translation:
```
"skins": {
        "choose_weapon": "Choose your {{label}}",
        "choose_weapon_default": "Skin",
        "categories": {
            "knifes": "Knife",
            "pistols": "Pistol",
            "rifles": "Rifle",
            "smg": "SMG",
            "machine_guns": "Machine Guns",
            "sniper_rifles": "Sniper Rifles",
            "shotguns": "Shotguns",
            "gloves": "Gloves",
            "agents": {
                "label": "Agents",
                "ct": "Counter Terrorist",
                "t": "Terrorist"
            }
        },
```
```
        "choose_weapon": "Choose your {{label}}",
```
The problem is that this translation would not be the same for other languages, at least in Portuguese-BR `Choose your` can have two translations, masculine and feminine.

Currently this really isn't a big problem, but would it be possible to implement the option to translate category by category?

- Choose your Skin
- Choose your Knife
- Choose your Agents

So everyone can translate individually.

**Comment by LielXD** [comment]
you dont have in your language the ability to choose label for all categories?

**Comment by crashzk** [comment]
> you dont have in your language the ability to choose label for all categories?

Unfortunately no, you think in a complicated language... hahaha

`Choose your` can be translated into both masculine and feminine gender.
