### ISSUE TITLE
[REQ] Support for clicking on photo or name to access steam profile

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#4]
I believe it is simple and useless at the moment, but the option of clicking on the player's photo or nickname to access their Steam profile would be interesting.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/373d894f-b9df-469e-8951-6c1bf67d8e27)

**Comment by LielXD** [comment]
will add it on the new release.
