### ISSUE TITLE
All buttons are not clickable

### ISSUE THREAD

**Issue by k1to0o** [LielXD/CS2-WeaponPaints-Website#46]
All buttons are not clickable. Agents tab icon not loading and I pressed Ctrl + F5. After that everything became unclickable

**Comment by LielXD** [comment]
You are using cloudflare?

**Comment by k1to0o** [comment]
Sorry, I don't know what this is. Where can I see if I'm using it or not?

**Comment by LielXD** [comment]
If you don't know what it is then that means u probably doesn't use cloudflare,
Where do you host your site?

**Comment by k1to0o** [comment]
I understand that this is bad, but I use free hosting https://byet.host/.

**Comment by k1to0o** [comment]
I used the previous version and everything worked, 
But when I switched to the new version, everything stopped working

**Comment by LielXD** [comment]
Send me your site link.

**Comment by k1to0o** [comment]
http://skinsservak.byethost8.com/

**Comment by LielXD** [comment]
Have you uploaded all the files?
It looks like it doesn't load the js file.
Please check if you have a file with the name: script.js,
If you have this file, maybe your host disabled js files from running, and you need to enable it somehow.

**Comment by k1to0o** [comment]
Thanks for the help! Just 7zip, for some reason I didn’t want to unzip the .js file
