### ISSUE TITLE
[REQ] Change Zeus x27 skin category

### ISSUE THREAD

**Issue by crashzk** [LielXD/CS2-WeaponPaints-Website#48]
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/df2d78fe-b0c5-4e65-b332-5e0798b1b365)

As you can see in CS2 itself, the Zeus x27 is not in the Pistol category. I wonder if it would be more interesting to leave it in its own category, like in CS2, Equipment/Utilities?

**Comment by LielXD** [comment]
It's some kind of a pistol.
