### ISSUE TITLE
Windows defender blocking download

### ISSUE THREAD

**Issue by everkk** [LielXD/CS2-WeaponPaints-Website#50]
Windows Defender blocking download. 
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/67241375/95b115c4-41d7-4564-9dfd-bb20353543f1)

**Comment by crashzk** [comment]
I don't think there's much it can do, but more details on the detection.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/32937653/85025279-d18c-4196-be2f-c7c0ec66699f)
