### ISSUE TITLE
Go Back button with wrong URL

### ISSUE THREAD

**Issue by hugocar2005** [LielXD/CS2-WeaponPaints-Website#68]
The button that I think was supposed to be the "Go Back" button is bugged for me. I don't know if its getting the wrong URL or something but I'd like some help to change it to make it work correctly.

![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/81335345/c17194de-8158-43e7-9b33-e9853c60bcf8)

**Comment by hugocar2005** [comment]
Or have the ability to remove the button completely since I can just open the skin-changing URL on a new tab directly from my main website.

**Comment by LielXD** [comment]
what exactly is the problem?

**Comment by hugocar2005** [comment]
The circled button.
![image](https://github.com/LielXD/CS2-WeaponPaints-Website/assets/81335345/dd4dae25-ce7f-4280-b664-4742bbcef938)

That button takes me to this website: 
https://www.000webhost.com/?utm_source=000webhostapp&utm_campaign=000_logo&utm_medium=website&utm_content=footer_img

I've never been to this website nor have any affiliation with it. My website IS hosted on 000webhost.com, but my URL is:
https://tascadozecm.000webhostapp.com/

So I need some help either changing it to the correct URL or removing the button completely. HTML and PHP are not my strong suit so I really have no idea where to change it and/or remove it.

**Comment by LielXD** [comment]
its a button your host adds because its a free service it has nothing to do with my website.

if you want free host service without any ads you can use https://infinityfree.com

**Comment by hugocar2005** [comment]
Oh ok. I thought of that possibility but since my other pages don't have that button I assumed it was something like a "Go Back" button. Thank you.
