### ISSUE TITLE
Error authorization

### ISSUE THREAD

**Issue by ReDcTiOn** [LielXD/CS2-WeaponPaints-Website#7]
An error appears when I click authorization
After refreshing the page, the error disappears

`Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/openid.php on line 190

Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/openid.php on line 320

Warning: Cannot modify header information - headers already sent by (output started at /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/openid.php:190) in /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/authorize.php on line 25`

**Comment by LielXD** [comment]
php version?

**Comment by ReDcTiOn** [comment]
> php version?

8.0

**Comment by LielXD** [comment]
does it happened all the time or how can I reproduce it?

**Comment by LielXD** [comment]
Fixed with new update please type your website link in the config:
```php
$Website_Domain = '';
```

**Comment by ReDcTiOn** [comment]
> Fixed with new update please type your website link in the config:
> 
> ```
> $Website_Domain = '';
> ```

Added $Website_Domain = 'cs2.ba3yka.ru';
The error has not gone away

Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/openid.php on line 190

Deprecated: Required parameter $update_claimed_id follows optional parameter $method in /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/openid.php on line 320

Warning: Cannot modify header information - headers already sent by (output started at /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/openid.php:190) in /var/www/u1117915/data/www/cs2.ba3yka.ru/includes/authorize.php on line 28

**Comment by ReDcTiOn** [comment]
The error does not always appear

**Comment by HerrMagiic** [comment]
Hey is there already a fix for this?

**Comment by brkvlr** [comment]
I'm getting the same error
