### ISSUE TITLE
[HELP]PHP Deprecated

### ISSUE THREAD

**Issue by yichen11818** [LielXD/CS2-WeaponPaints-Website#76]
Deprecated: Optional parameter $method declared before required parameter $update_claimed_id is implicitly treated as a required parameter in C:\inetpub\wwwroot\includes\openid.php on line 190

Deprecated: Optional parameter $params declared before required parameter $update_claimed_id is implicitly treated as a required parameter in C:\inetpub\wwwroot\includes\openid.php on line 190

Deprecated: Optional parameter $method declared before required parameter $update_claimed_id is implicitly treated as a required parameter in C:\inetpub\wwwroot\includes\openid.php on line 320

Deprecated: Optional parameter $params declared before required parameter $update_claimed_id is implicitly treated as a required parameter in C:\inetpub\wwwroot\includes\openid.php on line 320

Fatal error: Uncaught ErrorException: You must have either https wrappers or curl enabled. in C:\inetpub\wwwroot\includes\openid.php:55 Stack trace: #0 C:\inetpub\wwwroot\includes\authorize.php(25): LightOpenID->__construct('domain.com') #1 {main} thrown in C:\inetpub\wwwroot\includes\openid.php on line 55

**Comment by yichen11818** [comment]
php ver 8.4

**Comment by yichen11818** [comment]
i change to php 7.4than
```
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\inetpub\wwwroot\includes\openid.php on line 921
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\inetpub\wwwroot\includes\openid.php on line 921
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\inetpub\wwwroot\includes\openid.php on line 921
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\inetpub\wwwroot\includes\openid.php on line 921
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\inetpub\wwwroot\includes\openid.php on line 921
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\inetpub\wwwroot\includes\openid.php on line 921
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in C:\inetpub\wwwroot\includes\openid.php on line 921
``` :( i need help

**Comment by REllllll** [comment]
How did you solve this problem? I changed into the php7.4 and redirect to steam but then I can't login by steam. The steam authorize page just say something went wrong
